name: Accept Contributor Agreement
description: Accept the repository's Contributor Agreement
title: "[Agreement] Acceptance"
labels:
  - pending-agreement
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Contributor Agreement

        Blah blah CLA!

  - type: input
    id: repository
    attributes:
      label: Project repository
      description: Full name of the project repository for which this CLA is being agreed upon, e.g., `w3c-oss/canivc`.
      required: true

  - type: input
    id: pr
    attributes:
      label: Pull request
      description: URL of the pull request for which this CLA approval is required, if any, e.g., `https://github.com/w3c-oss/canivc/pull/70`.

  - type: checkboxes
    id: acceptance
    attributes:
      label: Agreement acceptance
      options:
        - label: I have read and agree to the Contributor Agreement for the repository listed above.
          required: true

  - type: checkboxes
    id: identity
    attributes:
      label: Identity confirmation
      options:
        - label: I am submitting this agreement for my own authenticated GitHub account.
          required: true
